<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <ProjectReference Include="..\PerformanceLab.Core\PerformanceLab.Core.csproj" />
    <ProjectReference Include="..\PerformanceLab.Infrastructure\PerformanceLab.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

</Project>
